//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistSoftware.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentistEntities : DbContext
    {
        public DentistEntities()
            : base("name=DentistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<ActivePatient> ActivePatients { get; set; }
        public DbSet<Appointment> Appointments { get; set; }
        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<Clinic> Clinics { get; set; }
        public DbSet<CustomMaterial> CustomMaterials { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<ImageCategory> ImageCategories { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Material> Materials { get; set; }
        public DbSet<MaterialTreatment> MaterialTreatments { get; set; }
        public DbSet<opperation> opperations { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<PatientHistory> PatientHistories { get; set; }
        public DbSet<PatientPayment> PatientPayments { get; set; }
        public DbSet<PaymentReceipt> PaymentReceipts { get; set; }
        public DbSet<Prescription> Prescriptions { get; set; }
        public DbSet<RecivingItem> RecivingItems { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Secretary> Secretaries { get; set; }
        public DbSet<Storage> Storages { get; set; }
        public DbSet<suppcontact> suppcontacts { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<Treatment> Treatments { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Warehouse> Warehouses { get; set; }
    }
}
