//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistSoftware.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class opperation
    {
        public int OpperationID { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> MaterialID { get; set; }
    }
}
