//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistSoftware.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int PatientID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> BrithDate { get; set; }
        public string gender { get; set; }
        public string E_mail { get; set; }
        public string Notice { get; set; }
    }
}
