//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistSoftware.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecivingItem
    {
        public int ReciveID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> SuppID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> ReciveDate { get; set; }
        public Nullable<int> StorageID { get; set; }
        public Nullable<bool> Recived { get; set; }
    }
}
