//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistSoftware.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.suppcontacts = new HashSet<suppcontact>();
        }
    
        public int SuppID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Countery { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string WebSite { get; set; }
        public string TaxFileNo { get; set; }
        public string TaxCommision { get; set; }
        public string TaxRegNo { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> openbalance { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<suppcontact> suppcontacts { get; set; }
    }
}
