//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistSoftware.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int WarehouseID { get; set; }
        public Nullable<int> StorageID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> Available { get; set; }
        public Nullable<int> Reserved { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
    }
}
