//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ActivePatient
{
    public int PatientID { get; set; }
    public int DoctorID { get; set; }
    public int ClinicID { get; set; }
}

public partial class Appointment
{
    public int AppointmentID { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<System.TimeSpan> Time { get; set; }
    public Nullable<int> DoctorID { get; set; }
    public Nullable<int> PatientID { get; set; }
    public string Reason { get; set; }
    public string Status { get; set; }
}

public partial class Clinic
{
    public int ClinicID { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public string Mobile { get; set; }
}

public partial class CustomMaterial
{
    public int CustomMaterialID { get; set; }
    public Nullable<System.DateTime> RequestDate { get; set; }
    public Nullable<System.DateTime> ReciveDate { get; set; }
    public Nullable<int> PatientID { get; set; }
    public Nullable<decimal> Cost { get; set; }
    public Nullable<int> DoctorID { get; set; }
    public string Description { get; set; }
    public string Name { get; set; }
}

public partial class Doctor
{
    public int DoctorID { get; set; }
    public Nullable<int> UserID { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public Nullable<int> Age { get; set; }
    public Nullable<System.DateTime> BrithDate { get; set; }
    public string Phone { get; set; }
    public string Mobile { get; set; }
    public string Address { get; set; }
    public string E_mail { get; set; }
    public Nullable<bool> Active { get; set; }
}

public partial class Image
{
    public int ImageID { get; set; }
    public string Name { get; set; }
    public string Notice { get; set; }
    public Nullable<int> appointmentID { get; set; }
    public Nullable<int> ImageCategoryID { get; set; }
    public Nullable<int> PatientID { get; set; }
    public string FullImageURL { get; set; }
    public string MediumImageURL { get; set; }
    public string MinImageURL { get; set; }
    public string LocalImageURL { get; set; }
}

public partial class ImageCategory
{
    public int ImageCategoryID { get; set; }
    public string Name { get; set; }
    public Nullable<decimal> Price { get; set; }
}

public partial class Material
{
    public int ItemID { get; set; }
    public string ItemName { get; set; }
    public string PartNumber { get; set; }
    public Nullable<int> CatID { get; set; }
    public Nullable<int> ProdCompany { get; set; }
    public string ScaleType { get; set; }
    public Nullable<int> ReOrder { get; set; }
    public Nullable<int> OpenBalance { get; set; }
    public Nullable<decimal> SalePrice { get; set; }
    public Nullable<int> TaxPerc { get; set; }
    public string Photo { get; set; }
    public Nullable<double> OBValue { get; set; }
    public Nullable<decimal> CostPrice { get; set; }
    public int Reserved { get; set; }
    public int Available { get; set; }
    public Nullable<int> Total { get; set; }
}

public partial class MaterialTreatment
{
    public int TeratmentID { get; set; }
    public int MaterialID { get; set; }
    public Nullable<double> Amonut { get; set; }
    public Nullable<decimal> MaterialCost { get; set; }
}

public partial class opperation
{
    public int OpperationID { get; set; }
    public string Name { get; set; }
    public string Color { get; set; }
    public Nullable<decimal> Price { get; set; }
    public Nullable<int> MaterialID { get; set; }
}

public partial class Patient
{
    public int PatientID { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public string Mobile { get; set; }
    public Nullable<int> Age { get; set; }
    public Nullable<System.DateTime> BrithDate { get; set; }
    public string gender { get; set; }
    public string E_mail { get; set; }
    public string Notice { get; set; }
}

public partial class PatientHistory
{
    public int HistoryID { get; set; }
    public Nullable<int> PatientID { get; set; }
    public string Name { get; set; }
    public string Descripation { get; set; }
}

public partial class PatientPayment
{
    public int PatientPaymentID { get; set; }
    public Nullable<int> PatientID { get; set; }
    public Nullable<decimal> TotalPrice { get; set; }
    public Nullable<decimal> PaidAmount { get; set; }
    public Nullable<int> ClinicID { get; set; }
}

public partial class PaymentReceipt
{
    public int ReceiptID { get; set; }
    public Nullable<System.DateTime> Date { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public Nullable<int> PatientPaymentID { get; set; }
    public string UserID { get; set; }
    public Nullable<int> ClinicID { get; set; }
}

public partial class Prescription
{
    public int PrescriptionID { get; set; }
    public string Notice { get; set; }
    public Nullable<int> MedicineID { get; set; }
    public Nullable<int> PatientID { get; set; }
    public Nullable<int> AppointmentID { get; set; }
}

public partial class RecivingItem
{
    public int ReciveID { get; set; }
    public Nullable<int> ItemID { get; set; }
    public Nullable<int> SuppID { get; set; }
    public Nullable<int> Amount { get; set; }
    public Nullable<System.DateTime> ExpireDate { get; set; }
    public Nullable<System.DateTime> ReciveDate { get; set; }
    public Nullable<int> StorageID { get; set; }
    public Nullable<bool> Recived { get; set; }
}

public partial class Role
{
    public int RoleID { get; set; }
    public string Name { get; set; }
    public string Note { get; set; }
}

public partial class Secretary
{
    public int SecretaryID { get; set; }
    public Nullable<int> UserID { get; set; }
    public string Name { get; set; }
    public string Gender { get; set; }
    public Nullable<System.DateTime> BrithDate { get; set; }
    public string Phone { get; set; }
    public string Mobile { get; set; }
    public string Address { get; set; }
    public string E_mail { get; set; }
    public Nullable<bool> Active { get; set; }
}

public partial class Storage
{
    public int StorageID { get; set; }
    public string Name { get; set; }
    public string Address { get; set; }
    public string Phone { get; set; }
    public string Mobile { get; set; }
    public Nullable<int> ClinicID { get; set; }
    public Nullable<bool> Active { get; set; }
}

public partial class suppcontact
{
    public int Id { get; set; }
    public Nullable<int> SuppId { get; set; }
    public string ContactName { get; set; }
    public string ContactTitel { get; set; }
    public string ContactDep { get; set; }
    public string City { get; set; }
    public string PhoneExt { get; set; }
    public string Phone { get; set; }
    public string Mobile { get; set; }
    public string EMail { get; set; }

    public virtual supplier supplier { get; set; }
}

public partial class supplier
{
    public supplier()
    {
        this.suppcontacts = new HashSet<suppcontact>();
    }

    public int SuppID { get; set; }
    public string CompanyName { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string Countery { get; set; }
    public string Phone1 { get; set; }
    public string Phone2 { get; set; }
    public string Fax { get; set; }
    public string WebSite { get; set; }
    public string TaxFileNo { get; set; }
    public string TaxCommision { get; set; }
    public string TaxRegNo { get; set; }
    public string Notes { get; set; }
    public Nullable<decimal> openbalance { get; set; }
    public string Type { get; set; }

    public virtual ICollection<suppcontact> suppcontacts { get; set; }
}

public partial class Treatment
{
    public int TeratmentID { get; set; }
    public string Description { get; set; }
    public Nullable<int> AppointmentID { get; set; }
    public Nullable<int> DoctorID { get; set; }
    public Nullable<int> PatientID { get; set; }
    public Nullable<int> OpperationID { get; set; }
}

public partial class User
{
    public int UserID { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public Nullable<int> RoleID { get; set; }
    public Nullable<int> ClienicID { get; set; }
}

public partial class Warehouse
{
    public int WarehouseID { get; set; }
    public Nullable<int> StorageID { get; set; }
    public Nullable<int> ItemID { get; set; }
    public Nullable<int> Available { get; set; }
    public Nullable<int> Reserved { get; set; }
    public Nullable<int> Total { get; set; }
    public Nullable<decimal> CostPrice { get; set; }
}
