//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> CatID { get; set; }
        public Nullable<int> ProdCompany { get; set; }
        public string ScaleType { get; set; }
        public Nullable<int> ReOrder { get; set; }
        public Nullable<int> OpenBalance { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> TaxPerc { get; set; }
        public string Photo { get; set; }
        public Nullable<double> OBValue { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public int Reserved { get; set; }
        public int Available { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
