//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentistSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int TeratmentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> AppointmentID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> OpperationID { get; set; }
    }
}
